### ISSUE TITLE
If the feed URL takes a long time to respond Cinnamon hangs when starting up

### ISSUE THREAD

**Issue by jonbrett** [jonbrett/cinnamon-feeds-applet#19]
The proxy that use was having some problems (I was getting HTTP 507 for every http request I made in my browser or otherwise).

During this time I restarted Cinnamon and noted that it never came back; it was waiting for something.... when I manually removed the feeds applet (using another virtual terminal) then Cinnamon restarted fine.

This makes me think that there is some problem with the way that the applet performs its http request. The applet is using a "async" request, but it does send that request at startup. Perhaps this is a problem.

The weather applet also uses similar soap apis for making http requests but didn't appear to cause the same issue during the downtime of the proxy (I had it enabled the whole time).

I'm not sure how easy it will be to reproduce this issue, but I thought it worthy of investigation anyway, even if that investigation is just looking at the difference in the usage of the soap functions in the weather applet, since the consequence (Cinnamon not starting) is quite severe!

**Comment by jake1164** [comment]
I have several very slow feeds and one that never responds and with the new layout in version 0.22 this is confirmed to be resolved.
