### ISSUE TITLE
Truncate feed item summary

### ISSUE THREAD

**Issue by jonbrett** [jonbrett/cinnamon-feeds-applet#26]
Originally reported by anandrkris on the spices website:
http://cinnamon-spices.linuxmint.com/applets/view/149

Sometimes the feed summary is too long, resulting in a very large tooltip. The feed summary should be automatically truncated to a fixed number of characters to avoid such issues.

**Comment by jake1164** [comment]
In release 0.17 this is actually implemented and limited to a manageable size, this helps with memory management as well.
