### ISSUE TITLE
Add a counter to applet icon for unread feeds

### ISSUE THREAD

**Issue by wizard974** [jonbrett/cinnamon-feeds-applet#27]
Maybe like gmail checker: http://cinnamon-spices.linuxmint.com/applets/view/117
Or a red point on top corner of the icon like "missed messages" on some phones.
With dark themes the change of icon is not really visible.

**Comment by jake1164** [comment]
@jonbrett any objections if I close this? I feel between the notification and the icon changing color I think this addresses the primary issue, knowing that a feed is available to be read.

**Comment by jonbrett** [comment]
No objections :-)

**Comment by jake1164** [comment]
Current notifications are sufficient, we can revisit in future if required.
