### ISSUE TITLE
Missing feeds

### ISSUE THREAD

**Issue by DuMuT6p** [jonbrett/cinnamon-feeds-applet#42]
Hello
I`ve noticed a bug with new feeds added.
Description: When removing and adding the applet again the feeds get reset to having only the default BBC feed. I tried both with adding a new feed and importing from a file. 
It seems trough that the notification keeps fetching the new feeds. A notification shows of another feed being updated, but it isn`t shown in the menu even after restart of the system.
This was encountered both in the official release from Cinnamon menu and cloning the repository.

**Comment by jake1164** [comment]
This is resolved with moving the folder up one level.
