### ISSUE TITLE
Add Linux Mint and Segfault blogs by default

### ISSUE THREAD

**Issue by jonbrett** [jonbrett/cinnamon-feeds-applet#44]
There have been requests on the spices website to add Linux Mint and Segfault blog feeds by default in the application. See: http://cinnamon-spices.linuxmint.com/applets/view/149

I would prefer the main feed to be a generic feed since this is most useful to the majority of users, yet I understand the request to pay respect to the Cinnamon community :)

Now that the applet supports multiple feeds we can add Linux Mint and Segfault as the 2nd and 3rd feeds.

Any objections?

**Comment by jake1164** [comment]
@jonbrett could you let me know what the history of this is, specifically if there was a reason you did not add them?

**Comment by jonbrett** [comment]
@jake1164 No reason for not adding them as a second and third feeds. I still think the first feed should be of more general interest, such as news.
