### ISSUE TITLE
Troubleshooting under Cinnamon 2.6.13 & Gentoo amd64

### ISSUE THREAD

**Issue by Myu-Unix** [jonbrett/cinnamon-feeds-applet#55]
(edited multiples times as I found new clues)

Hello !

First of all, thank you for your work on this applet :)

I'm trying to get the applet working under Cinnamon 2.6.13 & Gentoo but I did not succeed so far.

The applet loads fine on the "system tray" but stays at "Loading Feed" indefinitely.

It works if I try to run getFeed.py manually with python2.7 :

    python2.7 getFeed.py http://fxfeeds.mozilla.com/en-US/firefox/headlines.xml
    {"image": {"url": "http://news.bbcimg.co.uk/nol/shared/img/bbc_news_120x60.gif", "width": 120, "height": 60} 
*feed contents continues...*

So if I change my default python interpreter to python2.7, the applet works.

I fiddled with python path(s) on top of getFeed.py and into feedreader.js but it doesn't work? I *have* to change the default interpreter for some reasons.

Would you have a clue how to get it to work even if I leave python3 as default interpreter ? 

Have a nice day !

**Comment by jake1164** [comment]
Fixed python 2 / 3 comparability issues so now runs regardless of python version.
