### ISSUE TITLE
Update for Cinnamon 2.8

### ISSUE THREAD

**Issue by varlesh** [jonbrett/cinnamon-feeds-applet#57]
Title for RSS and buttons not available on Cinnamon 2.8
![2015-12-02 14 22 33](https://cloud.githubusercontent.com/assets/8083855/11529811/9a61cb94-9900-11e5-96ad-3fbc9a022b86.png)

**Comment by ikuria** [comment]
same problem here, checked some css values but without luck - the symbols and the rsstitle are right next to the appletpopup

**Comment by pehiv** [comment]
Im having the same issue .. Tried to fiddle with the CSS to no-avail .. I wish the cinnamon-applet documentation actually existed (not in the mood to tinker with the table in the applet with guess-work)
