### ISSUE TITLE
Move the data folder up one level?

### ISSUE THREAD

**Issue by jake1164** [jonbrett/cinnamon-feeds-applet#66]
I have noticed that removing the applet from the panel and moving it to a new panel will loose its history.  

use case: Using my laptop at work I have two monitors, however when I work from home I have one external (or just the laptop itself) and cinnamon cant create the panel (cinnamon issue). However removing the feed from the panel and adding it back to the monitor panel causes the applet to get a new ID, thus loosing its history.  

Should the data just be moved from the feeds@../instanceID/  folder to the feeds@ folder?

**Comment by jonbrett** [comment]
@jake1164 Thanks for all your suggestions and work on this.

In this particular case, the rationale for keeping the feeds data on a per-instance basis was because different instances may be using different feeds. If you think there is no risk of data from one applet instance polluting the other, please go ahead.

As you can tell, I am not actively working on this project at the moment. I'm happy to add you as a collaborator on this project so that you can merge pull requests, if that is agreeable to you.

Let me know

**Comment by jake1164** [comment]
Thats why I asked, was to get an idea of why.. I will do some more research to ensure its not an issue and perhaps look at some other applets and see how they handle it.
I would be happy to become a collaborator and handle the merges. Would you like me to handle the bug requests as well?
Thanks,Jason

Date: Tue, 12 Jan 2016 11:23:15 -0800

**Comment by jonbrett** [comment]
@jake1164 I have added you as a collaborator. You now have push access to the repo and should be able to deal with issues too.

Thanks for you help :)

**Comment by jake1164** [comment]
Made this change and in testing seems to working on my system.  When users upgrade to version 0.17 they may loose history unless they move the saved files from the subfolder to the root of the ~/.cinnamon/feeds...  folder.

**Comment by jake1164** [comment]
Can you give me access to the spices page so I can keep the releases updated?

http://cinnamon-spices.linuxmint.com/applets


From: jake1164@hotmail.com
To: reply@reply.github.com
Subject: RE: [cinnamon-feeds-applet] Move the data folder up one level? (#66)
Date: Tue, 12 Jan 2016 14:29:37 -0500




Thats why I asked, was to get an idea of why.. I will do some more research to ensure its not an issue and perhaps look at some other applets and see how they handle it.
I would be happy to become a collaborator and handle the merges. Would you like me to handle the bug requests as well?
Thanks,Jason

Date: Tue, 12 Jan 2016 11:23:15 -0800
