### ISSUE TITLE
Cinnamon 2.8

### ISSUE THREAD

**Issue by sadalavoaoj** [jonbrett/cinnamon-feeds-applet#70]
Hi there,

I tried to use this applet but when i try to make it run (add to painel) it gives me a error.
Did you tried on cinnamon 2.8 already?

Best regards.

**Comment by jake1164** [comment]
I run the app on 2.8.6 on fedora daily and test on the latest Mint / Cinnamon.  Do you have more details of what is happening?  You can also look in ~/.cinnamon/glass.log to see if there is an error message logged that gives detail of what the error is.

**Comment by jake1164** [comment]
Was this an upgrade? 

I seen an issue last night while trying different scenarios and found that it does sometimes fail on an upgrade.. basically there is a caching issue and restarting cinnamon (alt + F2, then r then enter) or just restarting the whole system resolved the issue.

**Comment by jake1164** [comment]
Do you still see this issue with the latest release (0.19)?

**Comment by jake1164** [comment]
Unable to reproduce, will re-open if required.
