### ISSUE TITLE
Manage feed issue

### ISSUE THREAD

**Issue by ricardojm** [jonbrett/cinnamon-feeds-applet#72]
Hi
For some reason, i can't manage feeds properly. I click in that option and nothing happens. I'm using cinnamon 2.8

**Comment by jake1164** [comment]
Hi,Is this an upgrade?Do you have any feeds showing up at all (BBC)?Does the feeds window open and it just does not save the feed?If you right click on the tray icon and press about can you indicate the version installed?

Date: Fri, 18 Mar 2016 09:42:12 -0700

**Comment by ricardojm** [comment]
this answer was fast lol. One at a time:
1- It is not a upgrade. I first installed in cinnamon 17.3
2- I do see BBC feeds
3- It doesn't open the feed window. The options 'mark all read' and 'manage feeds' doesn't work(probabily the option 'reload' too, but i can't confirm)
4- The version installed is v0.18

**Comment by jake1164** [comment]
Well 'mark all read' doesn't work for me either, I'll have to add that as a bug.
Can you try managing feeds from the manage applet interface?Right click on pane and select 'add applets to the pane'Select Feeds ReaderPress 'Configure' button at bottom of windowPress large 'Manage Feeds...' button
Does the 'Manage your feeds' window come up and work?

Date: Fri, 18 Mar 2016 10:06:33 -0700

**Comment by ricardojm** [comment]
No, unfortunally the manage window doesn't come up

**Comment by jake1164** [comment]
I have reproduced the bug, it appears on Mint based cinnamon when launching that window there is a permissions error. Oddly enough when I run the same code on a fedora based mint that window works.  I am looking into this but have not figured out what I broke yet.

Date: Fri, 18 Mar 2016 12:35:54 -0700

**Comment by mcvittal** [comment]
Hi,

I found a workaround for being unable to modify my feeds. I was affected by this bug on Linux Mint 17.3 Cinnamon as well. To fix it, I did the following:

    cd ~/.local/share/cinnamon/applets/feeds@jonbrettdev.wordpress.com
    chmod +x manage_feeds.py
    chown $USER manage_feeds.py

It now functions as expected.

**Comment by ricardojm** [comment]
Hi
Tried it here and now i can open the feed manager window
Thanks a lot

**Comment by mcvittal** [comment]
No problem. Hopefully this gets added into the init/install script.

**Comment by jake1164** [comment]
Thanks for your assistance, I will update the install this weekend.


Date: Wed, 23 Mar 2016 22:30:49 -0700

**Comment by jake1164** [comment]
I think I have a fix implemented (on my fork), I will need to test it on a fresh install of cinnamon over the weekend to ensure I have not broken anything new.

**Comment by jake1164** [comment]
Fixed in 0.19
