### ISSUE TITLE
Doesn't work with Gitlab activity feed

### ISSUE THREAD

**Issue by miloskroulik** [jonbrett/cinnamon-feeds-applet#77]
I tried to open activity feed from company Gitlab, but it didn't work (is there some way to debug issues?). It it something as:
`https://git.<mydomain>.com/<my-path>/<my-file>.atom?private_token=<token>`

I also tried to load it to Feedly and it worked fine. I would appreciate any help.

**Comment by jake1164** [comment]
Hi,In settings you can turn on additional bugging and then go to the ~/.cinnamon/ folder and look in the glass.log file for error and debug output.

Date: Tue, 12 Apr 2016 07:05:49 -0700

**Comment by miloskroulik** [comment]
Thanks. I did that and found out it loaded 0 items (there are several of them). No other errors appeared. Could it be because of lack of SSL support?

**Comment by jake1164** [comment]
Sounds like the most likely reason, the feed requires a login since its a work gitlab feed?

Date: Tue, 12 Apr 2016 07:21:26 -0700

**Comment by miloskroulik** [comment]
No, authentication is via the token, that is part of URL. Feedly didn't require any additional steps to display it.

**Comment by jake1164** [comment]
Ok, After some investigation I think its something in the Atom spec that differs from RSS, I will add Atom support to the list.

**Comment by jake1164** [comment]
Can you test the updated getFeed.py version in my fork?

https://github.com/jake1164/cinnamon-feeds-applet

Just download the getFeed.py file and replace (backup and then replace) the file in:

~/.local/share/cinnamon/applets/feeds@jonbrettdev.wordpress.com/

**Comment by miloskroulik** [comment]
I will (hopefully) test it later today, thanks!

**Comment by miloskroulik** [comment]
Sorry, didn't have time yesterday. Good news are that it seems to be working just fine for me. Thanks!
