### ISSUE TITLE
failed to import OPML file with utf-8 characters

### ISSUE THREAD

**Issue by hyOzd** [jonbrett/cinnamon-feeds-applet#94]
Feed manager failed to import an OPML file which contains UTF-8 characters. Here is the error message:

![screenshot from 2016-07-10 10 18 27](https://cloud.githubusercontent.com/assets/1479166/16712188/b65f81bc-4687-11e6-9ee6-782b5ca47da3.png)

**Comment by jake1164** [comment]
What Version did you have installed?

Any idea what feed caused it to crash?

**Comment by hyOzd** [comment]
My own blogs feed caused it to crash : )  https://hasanyavuz.ozderya.net

The title contains this character `Ö` which caused the problem.

**Comment by jake1164** [comment]
Can you right click on the tray icon and select about and let me know what the version number is on the window that pops up?

**Comment by hyOzd** [comment]
Version is 0.22

**Comment by jake1164** [comment]
Resolved issue to allow feeds with non-ascii characters to be imported.
